# 🐳 Docker Stack File (Swarm Mode)
# Note: This is designed for Docker Swarm ONLY
# ⚠️ Will not work with regular docker-compose due to port-binding with replicas

version: "3.9"

services:

  # 🔄 Redis Service (Key-Value Store)
  redis:
    image: redis:alpine
    networks:
      - frontend

  # 🗃️ PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  # 🗳️ Voting App Frontend
  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    networks:
      - frontend
    deploy:
      replicas: 2

  # 📊 Result App
  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend

  # ⚙️ Background Worker
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2

# 🔗 Networks and Volumes
networks:
  frontend:
  backend:

volumes:
  db-data:
